# Generated by Django 4.2.4 on 2023-09-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='sss', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
